server:
  port: 6002
spring:
  application:
    name: leadnews-wemedia-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.211.136:8848
    gateway:
      globalcors:
        cors-configurations:
          '[/]': # 匹配所有请求
            allowedOrigins: "*" #跨域处理 允许所有的域
            allowedMethods: # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        # wemedia管理
        - id: wemedia
          uri: lb://leadnews-wemedia
          predicates:
            - Path=/wemedia/**
          filters:
            - StripPrefix= 1
        # admin管理
        - id: admin
          uri: lb://leadnews-admin
          predicates:
            - Path=/admin/**  #http://localhost:6001/admin/api/v1/channel/list -->http://localhost:9001/api/v1/channel/list
          filters:
            - StripPrefix= 1